# fly.toml app configuration file
app = 'railway-platform-webapi-preproduction'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'   # Se para si no hay tráfico
  auto_start_machines = true    # Se arranca cuando llega tráfico
  min_machines_running = 0      # No mantiene máquinas activas
  processes = ['app']

# Configuración de VM dentro del tier gratuito
[[vm]]
  memory = '256mb'              # Límite gratuito
  cpus = 1                      # CPU compartida (gratis)
  cpu_kind = "shared"           # Evita CPU dedicada (de pago)
