app = "railway-platform-webapi"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"     # Apaga la máquina cuando no hay tráfico
  auto_start_machines = true      # La enciende automáticamente cuando llega tráfico
  min_machines_running = 0        # No mantiene máquinas encendidas
  processes = ["app"]

[[vm]]
  memory = "256mb"               
  cpus = 1
  cpu_kind = "shared"
